# Generated by Django 4.2.2 on 2023-06-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_description_article_descrtion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='descrtion',
            new_name='description',
        ),
    ]
